/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomePage: typeof import('./pages/home/ui/index.vue')['default']
    LoginPage: typeof import('./pages/login/ui/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Ui: typeof import('./components/postcard/ui/index.vue')['default']
  }
}
