/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/author/ui/': RouteRecordInfo<'/author/ui/', '/author/ui', Record<never, never>, Record<never, never>>,
    '/home/ui/': RouteRecordInfo<'/home/ui/', '/home/ui', Record<never, never>, Record<never, never>>,
    '/login/ui/': RouteRecordInfo<'/login/ui/', '/login/ui', Record<never, never>, Record<never, never>>,
    '/post/ui/': RouteRecordInfo<'/post/ui/', '/post/ui', Record<never, never>, Record<never, never>>,
  }
}
